// <auto-generated />
using System;
using AirportApp.ClassLibrary.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirportApp.ClassLibrary.Migrations
{
    [DbContext(typeof(AirportDbContext))]
    partial class AirportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.AddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AddOn_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BasePrice")
                        .HasColumnType("real")
                        .HasColumnName("Base_Price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("AddOns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 30f,
                            Name = "Extra Baggage"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 15f,
                            Name = "Priority Boarding"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 12f,
                            Name = "Seat Selection"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 45f,
                            Name = "Lounge Access"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Airport_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AirportCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Airport_Code");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.HasKey("Id");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirportCode = "LAX",
                            City = "Los Angeles"
                        },
                        new
                        {
                            Id = 2,
                            AirportCode = "JFK",
                            City = "New York"
                        },
                        new
                        {
                            Id = 3,
                            AirportCode = "ORD",
                            City = "Chicago"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Chat_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Chat_Status");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = 0,
                            UserId = 101
                        },
                        new
                        {
                            Id = 2,
                            Status = 0,
                            UserId = 102
                        },
                        new
                        {
                            Id = 3,
                            Status = 0,
                            UserId = 103
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Company_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acme Airlines"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Contoso Air"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SkyLink Airways"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ticket_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("Creation_Timestamp");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Description");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Subject");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("int")
                        .HasColumnName("Urgency_Level");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreationTimestamp = new DateTime(2026, 5, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 101,
                            CurrentStatus = 2,
                            Description = "System error when attempting to book",
                            SubcategoryId = 1,
                            Subject = "Cannot book flight",
                            UrgencyLevel = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreationTimestamp = new DateTime(2026, 5, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 102,
                            CurrentStatus = 0,
                            Description = "What is the baggage allowance?",
                            SubcategoryId = 3,
                            Subject = "Question about baggage",
                            UrgencyLevel = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreationTimestamp = new DateTime(2026, 5, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 103,
                            CurrentStatus = 0,
                            Description = "My card was declined during checkout",
                            SubcategoryId = 4,
                            Subject = "Payment failed",
                            UrgencyLevel = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreationTimestamp = new DateTime(2026, 5, 4, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = 101,
                            CurrentStatus = 2,
                            Description = "How long until my refund appears?",
                            SubcategoryId = 5,
                            Subject = "Refund pending",
                            UrgencyLevel = 1
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicketCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Category_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Category_Name");

                    b.Property<int>("CategoryUrgencyLevel")
                        .HasColumnType("int")
                        .HasColumnName("Default_Urgency_Level");

                    b.HasKey("Id");

                    b.ToTable("TicketCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Booking Issues",
                            CategoryUrgencyLevel = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "General Inquiry",
                            CategoryUrgencyLevel = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Payment Problems",
                            CategoryUrgencyLevel = 2
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicketSubcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Subcategory_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SubcategoryExternalReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("External_Reference_Id");

                    b.Property<string>("SubcategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Subcategory_Name");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("TicketSubcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ParentCategoryId = 1,
                            SubcategoryExternalReferenceId = 101,
                            SubcategoryName = "Booking Error"
                        },
                        new
                        {
                            Id = 2,
                            ParentCategoryId = 1,
                            SubcategoryExternalReferenceId = 102,
                            SubcategoryName = "Cancellation"
                        },
                        new
                        {
                            Id = 3,
                            ParentCategoryId = 2,
                            SubcategoryExternalReferenceId = 201,
                            SubcategoryName = "Flight Info"
                        },
                        new
                        {
                            Id = 4,
                            ParentCategoryId = 3,
                            SubcategoryExternalReferenceId = 301,
                            SubcategoryName = "Card Declined"
                        },
                        new
                        {
                            Id = 5,
                            ParentCategoryId = 3,
                            SubcategoryExternalReferenceId = 302,
                            SubcategoryName = "Refund Status"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password_Hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Email = "alice@bot.com",
                            MembershipId = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEFenwIGaS8Iw2zttM43jERpt162/RNiW0/ym+2RpOMoCb8e8fCktIbSBWj98U3wKKw==",
                            Phone = "",
                            Username = "alice"
                        },
                        new
                        {
                            Id = 102,
                            Email = "bob@chat.com",
                            MembershipId = 2,
                            PasswordHash = "AQAAAAIAAYagAAAAEC8U9uWPNk5tDFUJvCIq6GRveg1Fy5FLYZ+xVODxBz3VAv4lbceZAVCEeuSX9zfGmg==",
                            Phone = "",
                            Username = "bob"
                        },
                        new
                        {
                            Id = 103,
                            Email = "mia@example.com",
                            MembershipId = 3,
                            PasswordHash = "AQAAAAIAAYagAAAAEIVJmYMM7etHufWnOMzxARPwP5rhz/vg/5uq19PTDoVQQ7JZdI6D2vIJ5mxljdPz5A==",
                            Phone = "",
                            Username = "mia"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FAQEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FAQ_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Answer_Text");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<int>("HelpfulVotesCount")
                        .HasColumnType("int")
                        .HasColumnName("Helpful_Votes");

                    b.Property<int>("NotHelpfulVotesCount")
                        .HasColumnType("int")
                        .HasColumnName("Not_Helpful_Votes");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Question_Text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int")
                        .HasColumnName("View_Count");

                    b.HasKey("Id");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Click on the 'Forgot Password' link on the login page.",
                            Category = 1,
                            HelpfulVotesCount = 120,
                            NotHelpfulVotesCount = 5,
                            Question = "How do I reset my password?",
                            ViewCount = 150
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Standard baggage allowance is 2 checked bags. See add-ons for additional bags.",
                            Category = 2,
                            HelpfulVotesCount = 180,
                            NotHelpfulVotesCount = 10,
                            Question = "What is the baggage allowance?",
                            ViewCount = 200
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Yes, flight changes can be made up to 24 hours before departure, subject to availability.",
                            Category = 4,
                            HelpfulVotesCount = 160,
                            NotHelpfulVotesCount = 8,
                            Question = "Can I change my flight?",
                            ViewCount = 180
                        },
                        new
                        {
                            Id = 4,
                            Answer = "We accept major credit cards and selected digital wallets.",
                            Category = 4,
                            HelpfulVotesCount = 80,
                            NotHelpfulVotesCount = 2,
                            Question = "Which payment methods are accepted?",
                            ViewCount = 95
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Use the chat assistant or submit a support ticket from your account.",
                            Category = 4,
                            HelpfulVotesCount = 110,
                            NotHelpfulVotesCount = 3,
                            Question = "How do I contact support?",
                            ViewCount = 120
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FAQNode", b =>
                {
                    b.Property<int>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("node_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeId"));

                    b.Property<bool>("IsFinalAnswer")
                        .HasColumnType("bit")
                        .HasColumnName("is_final_answer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_text");

                    b.HasKey("NodeId");

                    b.ToTable("FAQNode", (string)null);

                    b.HasData(
                        new
                        {
                            NodeId = 1,
                            IsFinalAnswer = false,
                            QuestionText = "How can I help you today?"
                        },
                        new
                        {
                            NodeId = 2,
                            IsFinalAnswer = false,
                            QuestionText = "What is the issue with your baggage?"
                        },
                        new
                        {
                            NodeId = 3,
                            IsFinalAnswer = true,
                            QuestionText = "Check your email for a tracking link or visit the lost & found desk."
                        },
                        new
                        {
                            NodeId = 4,
                            IsFinalAnswer = true,
                            QuestionText = "Please file a \"Property Irregularity Report\" at the arrival hall."
                        },
                        new
                        {
                            NodeId = 5,
                            IsFinalAnswer = false,
                            QuestionText = "What would you like to do with your booking?"
                        },
                        new
                        {
                            NodeId = 6,
                            IsFinalAnswer = true,
                            QuestionText = "You can change your flight via the \"My Bookings\" section on our website."
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FAQOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("option_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("label");

                    b.Property<int?>("NextOptionId")
                        .HasColumnType("int")
                        .HasColumnName("next_option_id");

                    b.Property<int>("NodeId")
                        .HasColumnType("int")
                        .HasColumnName("node_id");

                    b.HasKey("OptionId");

                    b.HasIndex("NextOptionId");

                    b.HasIndex("NodeId");

                    b.ToTable("FAQOption", (string)null);

                    b.HasData(
                        new
                        {
                            OptionId = 1,
                            Label = "Baggage Issues",
                            NextOptionId = 2,
                            NodeId = 1
                        },
                        new
                        {
                            OptionId = 2,
                            Label = "Manage Booking",
                            NextOptionId = 5,
                            NodeId = 1
                        },
                        new
                        {
                            OptionId = 3,
                            Label = "Lost Baggage",
                            NextOptionId = 3,
                            NodeId = 2
                        },
                        new
                        {
                            OptionId = 4,
                            Label = "Damaged Baggage",
                            NextOptionId = 4,
                            NodeId = 2
                        },
                        new
                        {
                            OptionId = 5,
                            Label = "Change Flight Date",
                            NextOptionId = 6,
                            NodeId = 5
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Flight_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Departure_Date");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Flight_Number");

                    b.Property<int>("GateId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GateId");

                    b.HasIndex("RouteId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 5, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "AC100",
                            GateId = 1,
                            RouteId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 5, 5, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "CT200",
                            GateId = 2,
                            RouteId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 5, 6, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "SK300",
                            GateId = 3,
                            RouteId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 5, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "AC400",
                            GateId = 4,
                            RouteId = 4
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2026, 5, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "CT500",
                            GateId = 4,
                            RouteId = 5
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FlightTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ticket_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("PassengerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Passenger_Email");

                    b.Property<string>("PassengerFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Passenger_First_Name");

                    b.Property<string>("PassengerLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Passenger_Last_Name");

                    b.Property<string>("PassengerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Passenger_Phone");

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("Price");

                    b.Property<string>("Seat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Seat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("FlightTickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 1,
                            PassengerEmail = "johndoe@example.com",
                            PassengerFirstName = "John",
                            PassengerLastName = "Doe",
                            PassengerPhone = "",
                            Price = 199f,
                            Seat = "12A",
                            Status = "Booked",
                            UserId = 101
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 2,
                            PassengerEmail = "janeroe@example.com",
                            PassengerFirstName = "Jane",
                            PassengerLastName = "Roe",
                            PassengerPhone = "",
                            Price = 149f,
                            Seat = "14C",
                            Status = "Booked",
                            UserId = 102
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 3,
                            PassengerEmail = "mialane@example.com",
                            PassengerFirstName = "Mia",
                            PassengerLastName = "Lane",
                            PassengerPhone = "",
                            Price = 249f,
                            Seat = "8F",
                            Status = "Booked",
                            UserId = 103
                        },
                        new
                        {
                            Id = 4,
                            FlightId = 4,
                            PassengerEmail = "liamstone@example.com",
                            PassengerFirstName = "Liam",
                            PassengerLastName = "Stone",
                            PassengerPhone = "",
                            Price = 179f,
                            Seat = "5B",
                            Status = "Booked",
                            UserId = 101
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Gate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Gate_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Gate_Name");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("Gates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirportId = 1,
                            GateName = "A1"
                        },
                        new
                        {
                            Id = 2,
                            AirportId = 2,
                            GateName = "B2"
                        },
                        new
                        {
                            Id = 3,
                            AirportId = 3,
                            GateName = "C3"
                        },
                        new
                        {
                            Id = 4,
                            AirportId = 1,
                            GateName = "D4"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Membership_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("FlightDiscountPercentage")
                        .HasColumnType("real")
                        .HasColumnName("Flight_Discount_Percentage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightDiscountPercentage = 5f,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 2,
                            FlightDiscountPercentage = 15f,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 3,
                            FlightDiscountPercentage = 25f,
                            Name = "Platinum"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.MembershipAddonDiscount", b =>
                {
                    b.Property<int>("MembershipId")
                        .HasColumnType("int")
                        .HasColumnName("Membership_Id");

                    b.Property<int>("AddOnId")
                        .HasColumnType("int")
                        .HasColumnName("AddOn_Id");

                    b.Property<float>("DiscountPercentage")
                        .HasColumnType("real")
                        .HasColumnName("Discount_Percentage");

                    b.HasKey("MembershipId", "AddOnId");

                    b.HasIndex("AddOnId");

                    b.ToTable("Membership_Addon_Discounts", (string)null);

                    b.HasData(
                        new
                        {
                            MembershipId = 1,
                            AddOnId = 1,
                            DiscountPercentage = 10f
                        },
                        new
                        {
                            MembershipId = 1,
                            AddOnId = 2,
                            DiscountPercentage = 10f
                        },
                        new
                        {
                            MembershipId = 2,
                            AddOnId = 1,
                            DiscountPercentage = 20f
                        },
                        new
                        {
                            MembershipId = 2,
                            AddOnId = 2,
                            DiscountPercentage = 20f
                        },
                        new
                        {
                            MembershipId = 3,
                            AddOnId = 1,
                            DiscountPercentage = 30f
                        },
                        new
                        {
                            MembershipId = 3,
                            AddOnId = 2,
                            DiscountPercentage = 30f
                        },
                        new
                        {
                            MembershipId = 3,
                            AddOnId = 3,
                            DiscountPercentage = 30f
                        },
                        new
                        {
                            MembershipId = 3,
                            AddOnId = 4,
                            DiscountPercentage = 35f
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Message_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Message_Text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatId = 1,
                            SenderId = 101,
                            Text = "Hello! I need help with flights.",
                            Timestamp = new DateTimeOffset(new DateTime(2026, 5, 4, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            ChatId = 2,
                            SenderId = 102,
                            Text = "Hi, I have a question about membership.",
                            Timestamp = new DateTimeOffset(new DateTime(2026, 5, 4, 9, 5, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            ChatId = 3,
                            SenderId = 103,
                            Text = "Hello, I need support with my booking.",
                            Timestamp = new DateTimeOffset(new DateTime(2026, 5, 4, 9, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Review_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CleanlinessRating")
                        .HasColumnType("int")
                        .HasColumnName("Cleanliness_Rating");

                    b.Property<int>("DutyFreeRating")
                        .HasColumnType("int")
                        .HasColumnName("Duty_Free_Rating");

                    b.Property<int>("FlightExperienceRating")
                        .HasColumnType("int")
                        .HasColumnName("Flight_Experience_Rating");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("Message");

                    b.Property<int>("StaffFriendlinessRating")
                        .HasColumnType("int")
                        .HasColumnName("Staff_Friendliness_Rating");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Route_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Arrival_Time");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("Departure_Time");

                    b.Property<string>("RouteType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Route_Type");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirportId = 1,
                            ArrivalTime = new DateTime(2026, 5, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 180,
                            CompanyId = 1,
                            DepartureTime = new DateTime(2026, 5, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            RouteType = "Departure"
                        },
                        new
                        {
                            Id = 2,
                            AirportId = 2,
                            ArrivalTime = new DateTime(2026, 5, 5, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 150,
                            CompanyId = 2,
                            DepartureTime = new DateTime(2026, 5, 5, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            RouteType = "Arrival"
                        },
                        new
                        {
                            Id = 3,
                            AirportId = 3,
                            ArrivalTime = new DateTime(2026, 5, 6, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 220,
                            CompanyId = 3,
                            DepartureTime = new DateTime(2026, 5, 6, 7, 15, 0, 0, DateTimeKind.Unspecified),
                            RouteType = "Departure"
                        },
                        new
                        {
                            Id = 4,
                            AirportId = 1,
                            ArrivalTime = new DateTime(2026, 5, 7, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 160,
                            CompanyId = 1,
                            DepartureTime = new DateTime(2026, 5, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            RouteType = "Arrival"
                        },
                        new
                        {
                            Id = 5,
                            AirportId = 3,
                            ArrivalTime = new DateTime(2026, 5, 20, 15, 12, 0, 0, DateTimeKind.Unspecified),
                            Capacity = 50,
                            CompanyId = 2,
                            DepartureTime = new DateTime(2026, 5, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            RouteType = "Arrival"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Sender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Sender_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Discriminator");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email_Address");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Full_Name");

                    b.HasKey("Id");

                    b.ToTable("Senders");

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Discriminator = "Bot",
                            EmailAddress = "customer-support@cloudspritzers.com",
                            FullName = "Carlos"
                        });
                });

            modelBuilder.Entity("FlightTicket_AddOns", b =>
                {
                    b.Property<int>("Ticket_Id")
                        .HasColumnType("int");

                    b.Property<int>("AddOn_Id")
                        .HasColumnType("int");

                    b.HasKey("Ticket_Id", "AddOn_Id");

                    b.HasIndex("AddOn_Id");

                    b.ToTable("FlightTicket_AddOns", (string)null);
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Employee", b =>
                {
                    b.HasBaseType("AirportApp.ClassLibrary.Entity.Domain.Sender");

                    b.Property<int>("AssignedDepartment")
                        .HasColumnType("int")
                        .HasColumnName("Department");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discriminator = "Employee",
                            EmailAddress = "alice@acme.com",
                            FullName = "Alice Smith",
                            AssignedDepartment = 5
                        },
                        new
                        {
                            Id = 2,
                            Discriminator = "Employee",
                            EmailAddress = "bob@contoso.com",
                            FullName = "Bob Johnson",
                            AssignedDepartment = 3
                        },
                        new
                        {
                            Id = 3,
                            Discriminator = "Employee",
                            EmailAddress = "clara@skylink.com",
                            FullName = "Clara Davis",
                            AssignedDepartment = 0
                        },
                        new
                        {
                            Id = 4,
                            Discriminator = "Employee",
                            EmailAddress = "daniel@acme.com",
                            FullName = "Daniel Green",
                            AssignedDepartment = 2
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.User", b =>
                {
                    b.HasBaseType("AirportApp.ClassLibrary.Entity.Domain.Sender");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Discriminator = "User",
                            EmailAddress = "alice@bot.com",
                            FullName = "Alice Bot"
                        },
                        new
                        {
                            Id = 102,
                            Discriminator = "User",
                            EmailAddress = "bob@chat.com",
                            FullName = "Bob Chat"
                        },
                        new
                        {
                            Id = 103,
                            Discriminator = "User",
                            EmailAddress = "mia@example.com",
                            FullName = "Mia Passenger"
                        });
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Chat", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicket", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicketCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicketSubcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Creator");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicketSubcategory", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.ComplaintTicketCategory", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Customer", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FAQOption", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.FAQNode", "NextOption")
                        .WithMany()
                        .HasForeignKey("NextOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.FAQNode", null)
                        .WithMany("Options")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NextOption");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Flight", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Gate", "Gate")
                        .WithMany()
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gate");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FlightTicket", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Customer", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Gate", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Airport", "Airport")
                        .WithMany("Gates")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.MembershipAddonDiscount", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.AddOn", "AddOn")
                        .WithMany()
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Membership", "Membership")
                        .WithMany("AddonDiscounts")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Message", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Sender", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Review", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Route", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Airport", "Airport")
                        .WithMany()
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airport");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("FlightTicket_AddOns", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.AddOn", null)
                        .WithMany()
                        .HasForeignKey("AddOn_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FlightTicketAddOns_AddOn");

                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.FlightTicket", null)
                        .WithMany()
                        .HasForeignKey("Ticket_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FlightTicketAddOns_FlightTicket");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Employee", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Sender", null)
                        .WithOne()
                        .HasForeignKey("AirportApp.ClassLibrary.Entity.Domain.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.User", b =>
                {
                    b.HasOne("AirportApp.ClassLibrary.Entity.Domain.Sender", null)
                        .WithOne()
                        .HasForeignKey("AirportApp.ClassLibrary.Entity.Domain.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Airport", b =>
                {
                    b.Navigation("Gates");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.FAQNode", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("AirportApp.ClassLibrary.Entity.Domain.Membership", b =>
                {
                    b.Navigation("AddonDiscounts");
                });
#pragma warning restore 612, 618
        }
    }
}
